# Generated by Django 4.2 on 2026-02-26 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_cart_id_alter_cartitem_id_alter_category_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='gst_percent',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=5),
        ),
    ]
